services:
  - type: web
    name: stoic-companion
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python prepare_vectorstore.py

    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT